import os
import shutil

class PhpEnvLauncher:
    def __init__(self, project_path, name="php.env.bat"):
        self.project_path = os.path.abspath(project_path)
        self.venv_activate = os.path.join(self.project_path, ".venv", "Scripts", "activate.bat")
        self.name = name

    def create(self):
        content = f"""@echo off
:: Auto-generated by Python
set "PROJECT_PATH={self.project_path}"
set "VENV_PATH={self.venv_activate}"

powershell -Command "Start-Process cmd -ArgumentList '/k cd /d \\"%PROJECT_PATH%\\" ^&^& call \\"%VENV_PATH%\\"' -Verb RunAs"
"""
        with open(self.name, "w") as f:
            f.write(content)

        # Copy to System32 for global access
        system32 = os.path.join(os.environ["WINDIR"], "System32")
        dest = os.path.join(system32, self.name)
        try:
            shutil.copy2(self.name, dest)
            print(f"[SUCCESS] Installed globally: {dest}")
        except PermissionError:
            print(f"[WARNING] Could not copy to {system32}. Run script as Administrator.")
        return dest

# Example usage
if __name__ == "__main__":
    project_dir = r"C:\Users\YourName\MyProject"
    PhpEnvLauncher(project_dir).create()
